name = "ai-design-tool"
compatibility_date = "2025-04-17"
main = "./src/worker.ts"
compatibility_flags = ["nodejs_compat"]


[assets]
not_found_handling = "single-page-application"

[[durable_objects.bindings]]
name = "DesignAgent"
class_name = "DesignAgent"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["DesignAgent"]